apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app: app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd-server:v2.6.6
        ports:
        - containerPort: 8081

