apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app: argocd-server
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
  type: NodePort 

